config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  get '/charlie/index', to: 'charlie#index', as: 'charlie_index'
  get '/trey/index', to: 'trey#index', as: 'trey_index'
  get '/tristan/index', to: 'tristan#index', as: 'tristan_index'
  get '/miles/index', to: 'miles#index', as: 'miles_index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/srouting.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :comments, only: [:create]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  validates :page, presence: true
end

app/models/team_member.rb
# app/models/team_member.rb
class TeamMember < ApplicationRecord
  geocoded_by :hometown
  after_validation :geocode, if: ->(obj){ obj.hometown.present? and obj.hometown_changed? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_signed_in?
end

app/controllers/charlie_controller.rb
class CharlieController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]  # Ensure the user is signed in for comment creation

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      @comments = Comment.all
      respond_to do |format|
        format.turbo_stream
      end
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :page)
  end

  def show
    @page = controller_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @team_members = TeamMember.all
  end
end

app/controllers/miles_controller.rb
class MilesController < ApplicationController
  def index
  end
end

app/controllers/trey_controller.rb
class TreyController < ApplicationController
  def index
  end
end

app/controllers/tristan_controller.rb
class TristanController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charlie_helper.rb
module CharlieHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/miles_helper.rb
module MilesHelper
end

app/helpers/trey_helper.rb
module TreyHelper
end

app/helpers/tristan_helper.rb
module TristanHelper
end

app/views/charlie/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= "Charlie's Portfolio - Ballmer Peak Portfolio" %></title>
  <%= stylesheet_link_tag 'charlieStyles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.9.0/viewer.min.js"></script>
</head>
<body>
<header style="background-image: url('<%= asset_path("charliesImages/outerSpace.webp") %>'); background-size: cover; background-position: center; background-repeat: no-repeat;">
  <h1>Charlie's Portfolio</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
    </ul>
  </nav>
</header>
<main>
  <section class="introduction">
    <h2>About Me</h2>
    <p>Hello! My name is Charles David Wilmot II, but you can call me Charlie.
      I have a diverse range of interests spanning real estate, space exploration,
      volleyball, piano, fishing, machine learning, AI, systems engineering, and
      computer science and engineering. I am passionate about solving complex problems and
      constantly seeking out new challenges.</p>
  </section>

  <!-- New Section: Undergraduate Research -->
  <section class="undergraduate-research">
    <h2>Undergraduate Research Recognition</h2>
    <%= image_tag 'charliesImages/bannerPhoto.jpeg', alt: 'Charlie in the Downtown Banner Campaign', class: 'feature-image small-image' %>
    <p>I was recently selected for the downtown banner campaign for my undergraduate research work. This has been a great honor and a testament to the hard work and dedication I have put into my studies and research activities.</p>
  </section>

  <!-- New Section: Volleyball -->
  <section class="volleyball">
    <h2>Volleyball</h2>
    <%= image_tag 'charliesImages/volleyballPhoto.JPG', alt: 'Charlie Fishing', class: 'feature-image small-image' %>
    <p>I have played Volleyball here all four years and am currently the president of the club.</p>
  </section>

  <!-- New Section: Fishing Hobby -->
  <section class="fishing-hobby">
    <h2>Fishing Adventures</h2>
    <div class="fishing-images">
      <%= image_tag 'charliesImages/fishPhoto.jpg', alt: 'Charlie Fishing', class: 'fishing-image' %>
      <%= image_tag 'charliesImages/fishPhoto2.jpeg', alt: 'Charlie Fishing', class: 'fishing-image' %>
      <%= image_tag 'charliesImages/fishPhoto3.jpeg', alt: 'Charlie Fishing', class: 'fishing-image' %>
    </div>
    <p>Fishing has always been a passion of mine. In this picture, I am proud to have caught a beautiful blue gill, a large bass, and mahi mahi.</p>
  </section>

  <!-- New Section: Work at Space Force -->
  <section class="space-force">
    <h2>Space Force Experience</h2>
    <div class="space-force-images">
      <%= image_tag 'charliesImages/spaceForce.PNG', alt: 'Charlie at Space Force', class: 'space-force-image' %>
      <%= image_tag 'charliesImages/spaceForce2.PNG', alt: 'Charlie at Space Force', class: 'space-force-image' %>
      <%= image_tag 'charliesImages/spaceForce3.PNG', alt: 'Charlie at Space Force', class: 'space-force-image' %>
    </div>
    <p>I had the unique opportunity to work at the Space Force, contributing to important missions and projects. I am excited to return and continue my career there after graduation.</p>
  </section>

  <!-- New Section: Eagle Scout -->
  <section class="eagle-scout">
    <h2>Eagle Scout</h2>
    <%= image_tag 'charliesImages/eagleScout.JPG', alt: 'Eagle Scout', class: 'feature-image small-image' %>
    <p>I earned the rank of Eagle Scout in 2019 and served as Senior Patrol Leader (SPL) my last year of Boy Scouts</p>
  </section>

  <!-- New Section: Eagle Scout -->
  <section class="space">
    <h2>Space</h2>
    <%= image_tag 'charliesImages/space.JPG', alt: 'Eagle Scout', class: 'feature-image small-image' %>
    <p>Every since I was a little kid, I have been infatuated with Space</p>
  </section>

  <section class="projects">
    <h2>My Projects</h2>
    <div class="project">
      <h3>ML/AI Data Analytics Project: SSJI Disease</h3>
      <p>This project focused on analyzing and predicting the spread of SSJI disease using machine learning and AI techniques.</p>
      <!-- Add more details, images, links, etc. -->
    </div>
    <div class="project">
      <h3>MAGIC Project - NASA TRACERS Mission</h3>
      <p>I had the incredible opportunity to be selected as a software engineer on the MAGIC project, a part of NASA's TRACERS mission.</p>
      <!-- Add more details, images, links, etc. -->
    </div>
    <!-- Add more projects as needed -->
    <div class="project">
      <h3>Optimizing Model Selection in Low Variability Datasets with Imbalanced Dependent Variables</h3>
      <p>Using different ML models to predict results with low variability datasets</p>
      <iframe src='<%= "#{request.base_url}/pdfs/AIMLpaper.pdf" %>' width="100%" height="600px" allowfullscreen webkitallowfullscreen></iframe>
    </div>
    <div class="project">
      <h3>Environmental Sensor</h3>
      <p>This embedded systems project focused on creating an Environmental Station to measure temperature, pressure, humidity, and other atmospheric readings</p>
      <!-- Add more details, images, links, etc. -->
    </div>
  </section>

  <section class="skills-carousel">
    <h2>Skills & Technologies</h2>
    <div class="carousel">
      <div class="carousel-container">
        <div class="carousel-slide">
          <%= image_tag 'icons/python.png', alt: 'Python' %>
          <%= image_tag 'icons/java.png', alt: 'Java' %>
          <%= image_tag 'icons/cpp.png', alt: 'C++' %>
          <%= image_tag 'icons/c.png', alt: 'C' %>
          <%= image_tag 'icons/ruby.png', alt: 'Ruby' %>
          <%= image_tag 'icons/matlab.jpg', alt: 'MATLAB' %>
          <%= image_tag 'icons/html.png', alt: 'HTML' %>
          <%= image_tag 'icons/css.png', alt: 'CSS' %>
          <%= image_tag 'icons/js.png', alt: 'JS' %>
          <%= image_tag 'icons/github.png', alt: 'GitHub' %>
          <%= image_tag 'icons/jira.png', alt: 'JIRA' %>
          <%= image_tag 'icons/pandas.png', alt: 'Pandas' %>
          <%= image_tag 'icons/numpy.png', alt: 'NumPy' %>
          <%= image_tag 'icons/scikit-learn.png', alt: 'SciKit Learn' %>
          <%= image_tag 'icons/seaborn.png', alt: 'Seaborn' %>
          <%= image_tag 'icons/tensorflow.png', alt: 'tensorflow' %>
          <%= image_tag 'icons/mongodb.png', alt: 'MongoDB' %>
          <%= image_tag 'icons/postgres.png', alt: 'Postgres' %>
          <%= image_tag 'icons/neo4j.png', alt: 'Neo4J' %>
          <%= image_tag 'icons/jetbrains.png', alt: 'Jetbrains' %>
          <%= image_tag 'icons/vscode.png', alt: 'VS Code' %>
          <%= image_tag 'icons/arduino.png', alt: 'Arduino' %>
          <%= image_tag 'icons/realestate.png', alt: 'RealEstate' %>
          <%= image_tag 'icons/fishing.png', alt: 'Fishing' %>
          <%= image_tag 'icons/volleyball.png', alt: 'Volleyball' %>
        </div>
      </div>
    </div>
  </section>

  <section class="contact">
    <h2>Contact Me</h2>
    <p>Feel free to reach out to me for any inquiries or collaborations. I'm always open to discuss new opportunities and projects!</p>
    <p>Email: <a href="mailto:chazwilmot@gmail.com">chazwilmot@gmail.com</a></p>
    <p>Phone: (310) 779-8746</p>
    <p>LinkedIn: <a href="https://www.linkedin.com/in/charles-wilmot/" target="_blank">Charles Wilmot</a></p>
  </section>

  <section class="comments" id="comments">
    <% if user_signed_in? %>
      <h2>Comments</h2>
      <%= render 'comments/comment_list', comments: Comment.where(page: 'charlie').order(created_at: :desc).limit(10) %>
      <div class="comment-form" id="commentForm">
        <%= render 'comments/form', comment: Comment.new %>
      </div>
    <% end %>
  </section>
</main>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var options = {}; // You can customize the options if needed
        var viewer = new Viewer(document.body, options);
    });
</script>

<footer>
  <p>© <%= Time.now.year %> Ballmer Peak Portfolio</p>
</footer>
</body>
</html>

app/views/comments/_comment.html.erb
<!-- app/views/comments/_comment.html.erb -->

<li><strong><%= comment.user.email.split('@').first %>:</strong> <%= comment.content %></li>

app/views/comments/_comment_list.html.erb
<!-- app/views/comments/_comment_list.html.erb -->

<ul id="commentList">
  <%= render partial: 'comments/comment', collection: comments %>
</ul>

app/views/comments/_form.html.erb
<!-- app/views/comments/_form.html.erb -->

<h3>Leave a comment:</h3>
<%= form_with(model: comment, remote: true) do |form| %>
  <label for="comment">Comment:</label><br>
  <%= form.hidden_field :page, value: controller_name %>
  <%= form.text_area :content, id: 'comment_content', rows: '4', cols: '50' %><br><br>
  <%= form.submit 'Submit', id: 'commentSubmit' %>
<% end %>

app/views/comments/create.turbo_stream.erb
<!-- app/views/comments/create.turbo_stream.erb -->

<%= turbo_stream.append(
      :commentList,
      partial: 'comments/comment',
      locals: { comment: @comment }
    ) %>

<%= turbo_stream.replace(
      :commentForm,
      partial: 'comments/form',
      locals: { comment: Comment.new }
    ) %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ballmer Peak Portfolio</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "styles", media: "all", "data-turbolinks-track": "reload" %>
</head>
<body>
<div class="top-bar">
  <div class="dropdown">
    <button class="dropdown">Team Members</button>
    <div class="dropdown-content">
      <%= user_signed_in? ? link_to("Charlie", charlie_index_path) : content_tag(:span, "Charlie") %>
      <%= user_signed_in? ? link_to("Trey", trey_index_path) : content_tag(:span, "Trey") %>
      <%= user_signed_in? ? link_to("Tristan", tristan_index_path) : content_tag(:span, "Tristan") %>
      <%= user_signed_in? ? link_to("Miles", miles_index_path) : content_tag(:span, "Miles") %>
    </div>
  </div>
  <div class="toogleButton">
    <button onclick="toggleTheme()">Toggle Theme</button>
  </div>
  <nav class="auth-nav">
    <ul>
      <% if user_signed_in? %>
        <li><a href="#comments">Comment</a></li>
        <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <li><%= link_to "Sign Up", "/users/sign_up" %></li>
        <li><%= link_to "Login", "/users/sign_in" %></li>
      <% end %>
    </ul>
  </nav>
</div>
<header style="background-image: url('<%= asset_path("mountain.jpeg") %>'); background-size: cover; background-position: center; background-repeat: no-repeat;">
  <div class="header-container">
    <h1>Ballmer Peak Portfolio</h1>
  </div>
</header>
<main>
  <section class="intro">
    <p>Welcome to the Ballmer Peak Portfolio! Login or Signup to get to know our amazing team members below:</p>
  </section>
  <section class="team-members">
    <h2>Meet the Team</h2>
    <ul>
      <li>
        <%= user_signed_in? ? link_to(charlie_index_path) do %>
          <div class="team-member">
            <%= image_tag("charlie.jpeg", alt: "Charlie") %>
            <span>Charlie</span>
          </div>
        <% end : image_tag("charlie.jpeg", alt: "Charlie", class: "team-member") %>
      </li>
      <li>
        <%= user_signed_in? ? link_to(trey_index_path) do %>
          <div class="team-member">
            <%= image_tag("trey.jpeg", alt: "Trey") %>
            <span>Trey</span>
          </div>
        <% end : image_tag("trey.jpeg", alt: "Trey", class: "team-member") %>
      </li>
      <li>
        <%= user_signed_in? ? link_to(tristan_index_path) do %>
          <div class="team-member">
            <%= image_tag("tristan.jpeg", alt: "Tristan") %>
            <span>Tristan</span>
          </div>
        <% end : image_tag("tristan.jpeg", alt: "Tristan", class: "team-member") %>
      </li>
      <li>
        <%= user_signed_in? ? link_to(miles_index_path) do %>
          <div class="team-member">
            <%= image_tag("miles.jpeg", alt: "Miles") %>
            <span>Miles</span>
          </div>
        <% end : image_tag("miles.jpeg", alt: "Miles", class: "team-member") %>
      </li>
    </ul>
  </section>

  <section class="our-work">
    <h2>Our Work</h2>

    <div class="lab">
      <%= image_tag("lab1.jpeg", alt: "Lab 1 Project") %>
      <h3>Lab 1: Temperature Box</h3>
      <p>A brief description of what Lab 1 was about and what technologies or concepts were covered.</p>
      <%= link_to "View More", "https://github.com/Senior-Design-Ballmer-Peak/Lab-1", class: "view-more" %>
    </div>

    <div class="lab">
      <%= image_tag("lab2.jpeg", alt: "Lab 2 Project") %>
      <h3>Lab 2: Electric Eye</h3>
      <p>A brief description of what Lab 2 was about and what technologies or concepts were covered.</p>
      <%= link_to "View More", "https://github.com/Senior-Design-Ballmer-Peak/Lab-2", class: "view-more" %>
    </div>

    <div class="lab">
      <%= image_tag("rocket.png", alt: "CAPSTONE") %>
      <h3>Future Work - Rocket</h3>
      <p>A brief description...</p>
      <%= link_to "View More", "https://www.youtube.com/watch?v=vPF8EeFifvk", class: "view-more" %>
    </div>
  </section>

  <div class="lab">
    <h2>Team member hometowns</h2>
  </div>
  <div id="team-map" style="height: 400px;"></div>

  <section class="comments" id="comments">
    <% if user_signed_in? %>
      <div id="team-map" style="height: 400px;"></div>
      <h2>Comments</h2>
      <%= render 'comments/comment_list', comments: Comment.where(page: 'home').order(created_at: :desc).limit(10) %>
      <div class="comment-form" id="commentForm">
        <%= render 'comments/form', comment: Comment.new %>
      </div>
    <% end %>
  </section>
</main>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var map = L.map('team-map').setView([20, 0], 2); // Set a default view

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        <% @team_members.each do |member| %>
        <% if member.latitude && member.longitude %>
        var marker = L.marker([<%= member.latitude %>, <%= member.longitude %>]).addTo(map);
        marker.bindPopup("<strong><%= member.name %></strong><br><%= member.hometown %>");
        <% end %>
        <% end %>
    });

    function toggleTheme() {
        const currentTheme = document.documentElement.getAttribute('data-theme');
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('data-theme', newTheme);

        localStorage.setItem('theme', newTheme);
    }

    document.addEventListener('DOMContentLoaded', () => {
        const savedTheme = localStorage.getItem('theme') || 'light'; // Default to light theme
        document.documentElement.setAttribute('data-theme', savedTheme);
    });

</script>

<footer>
  <p>© 2023 Ballmer Peak Portfolio</p>
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tristan/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= "Tristan's Portfolio - Ballmer Peak Portfolio" %></title>
  <%= stylesheet_link_tag 'tristanStyles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.9.0/viewer.min.js"></script>
</head>
<body>
<header>
  <h1>Tristan's Portfolio</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
    </ul>
  </nav>
</header>
<main>
  <section class="introduction">
    <h2>About Me</h2>
    <p class="limited-width"> Hey there, I'm Tristan, a student at the University of Iowa, majoring in computer science and engineering. My focus during my time here has been on delving into the world of embedded systems. It's an area that has captivated my interest, blending hardware and software intricacies to create efficient systems that power various technologies we use daily.
      In my free time, I love immersing myself in a variety of hobbies that keep me engaged and excited. Among these, you'll often find me tinkering away with my 3D printer, turning ideas into tangible creations. I also cherish the serene moments spent hiking, where nature's beauty never fails to captivate me. And when winter arrives, I eagerly embrace the thrill of Nordic skiing, relishing the crisp air and the exhilaration of gliding through snow-covered landscapes.
    </p>
  </section>

  <section class="internship">
    <h2>Internship at Herzog</h2>
    <%= image_tag 'tristanImages/herzog-intern-team.jpeg', alt: 'Summer 2023 interns at the Herzog Cedar Rapids office', class: 'feature-image small-image' %>
    <p class="limited-width">Summer 2023 I worked as a Software Engineering Intern for Herzog Technologies Inc. I gained valuable experience working in a team and learning new technologies.</p>
  </section>

  <section class="teaching-assistant">
    <h2>Undergraduate Teaching Assistant</h2>
    <%= image_tag 'tristanImages/ta-teaching.jpg', alt: 'Teaching a lab about FPGAs', class: 'feature-image small-image' %>
    <p class="limited-width">The past several semesters I have worked for the ECE department as a teaching assistant. I have TA'd for several classes including Digital Design, Computers in Engineering, and Intro to Engineering Computing.</p>
  </section>

  <section class="embedded-project">
    <h2>Environmental Sensor</h2>
    <%= image_tag 'tristanImages/Embedded-weather-station.jpg', alt: 'Breadboard with an LCD displaying the temperature and air quality', class: 'feature-image small-image' %>
    <p class="limited-width">Myself and <%= link_to 'Charlie', charlie_index_path %> designed and implemented a fully functional environmental monitoring system, using an ATMega328p programmed using C.
      The system monitored temperature, air quality, humidity, and pressure.</p>
  </section>

  <section class="hobbies">
    <h2>Hobbies</h2>
    <div class="hobby-images">
      <%= image_tag 'tristanImages/hiking-missouri.jpg', alt: 'Hiking in Meramec State park in Missouri', class: 'feature-image small-image' %>
      <%= image_tag 'tristanImages/my-3D-printer.jpg', alt: '3D printer (Sovol SV06)', class: 'feature-image small-image' %>
      <%= image_tag 'tristanImages/north-shore-picture.jpg', alt: 'On the north shore of lake superior', class: 'feature-image small-image' %>
    </div>

    <p class="limited-width">My hobbies include spending time outside either hiking or skiing, and exploring the world of additive manufacturing with my 3D printer.</p>
  </section>

  <section class="skills-carousel">
    <h2>Skills & Technologies</h2>
    <div class="carousel">
      <div class="carousel-container">
        <div class="carousel-slide">
          <%= image_tag 'icons/c.png', alt: 'C' %>
          <%= image_tag 'icons/cpp.png', alt: 'C++' %>
          <%= image_tag 'icons/csharp.png', alt: 'C#' %>
          <%= image_tag 'icons/dotnet.png', alt: '.Net' %>
          <%= image_tag 'icons/java.png', alt: 'Java' %>
          <%= image_tag 'icons/python.png', alt: 'Python' %>
          <%= image_tag 'icons/ruby.png', alt: 'Ruby' %>
          <%= image_tag 'icons/ruby-on-rails.png', alt: 'Ruby on Rails' %>
          <%= image_tag 'icons/angular.png', alt: 'Angular' %>
          <%= image_tag 'icons/html.png', alt: 'HTML' %>
          <%= image_tag 'icons/css.png', alt: 'CSS' %>
          <%= image_tag 'icons/typescript.png', alt: 'Typescript' %>
          <%= image_tag 'icons/haskell.png', alt: 'Haskell' %>
          <%= image_tag 'icons/assembly.png', alt: 'Assembly' %>
          <%= image_tag 'icons/matlab.png', alt: 'MatLab' %>
          <%= image_tag 'icons/mongodb.png', alt: 'MongoDB' %>
          <%= image_tag 'icons/postgres.png', alt: 'Postgres' %>
          <%= image_tag 'icons/neo4j.png', alt: 'Neo4J' %>
          <%= image_tag 'icons/redis.png', alt: 'Redis' %>
          <%= image_tag 'icons/bash.png', alt: 'Bash' %>
          <%= image_tag 'icons/ubuntu.png', alt: 'Ubuntu' %>
          <%= image_tag 'icons/jetbrains.png', alt: 'Jetbrains' %>
          <%= image_tag 'icons/vscode.png', alt: 'VS Code' %>
          <%= image_tag 'icons/git.png', alt: 'Git' %>
          <%= image_tag 'icons/PlatformIO.png', alt: 'PlatforIO' %>
          <%= image_tag 'icons/arduino.png', alt: 'Arduino' %>
          <%= image_tag 'icons/jira.png', alt: 'Jira' %>
        </div>
      </div>
    </div>
  </section>

  <section class="resume">
    <h2>Resume</h2>
    <iframe src='<%= "#{request.base_url}/pdfs/firmware resume 2023.pdf" %>' width="100%" height="600px" allowfullscreen webkitallowfullscreen></iframe>
  </section>

  <script>
      document.addEventListener('DOMContentLoaded', function () {
          var options = {}; // You can customize the options if needed
          var viewer = new Viewer(document.body, options);
      });
  </script>

  <section class="comments" id="comments">
    <% if user_signed_in? %>
      <h2>Comments</h2>
      <%= render 'comments/comment_list', comments: Comment.where(page: 'tristan').order(created_at: :desc).limit(10) %>
      <div class="comment-form" id="commentForm">
        <%= render 'comments/form', comment: Comment.new %>
      </div>
    <% end %>
  </section>

  <section class="contact">
    <h2>Contact Me</h2>
    <p>Feel free to reach out to me for any inquiries or collaborations.</p>
    <p>If I don't respond to your email I might have missed it, try messaging me on LinkedIn!</p>
    <p>Email: <a href="mailto:tristan-pawlenty@uiowa.edu">tristan-pawlenty@uiowa.edu</a></p>
    <p>LinkedIn: <a href="https://www.linkedin.com/in/tristan-pawlenty" target="_blank">tristan-pawlenty</a></p>
  </section>
</main>
<footer>
  <p>© <%= Time.now.year %> Ballmer Peak Portfolio</p>
</footer>
</body>
</html>